- name: ----- pull docker image -----
  docker_image:
    name: nginx
    source: pull # build,push,load
  tags: [docker_pull]

- name: 
  docker_image:
    name: alpine:latest
    source: push
    







